os: linux
dist: xenial

language: node_js

script:
  - NODE_ENV=production make build
  - make lint
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make archive

deploy:
  provider: releases
  api_key:
    secure: Lk7KQ04EqsFownpIlOg9c3fVhm5C+OTynnKvSqpLcvqqQka8qYUKtl8G+AxmXmidHnhPoLzzrHHFc+NkW5amh80qj4LsrYEFkrXcp6YaPFcCjL1jLphvSjVtrYVCen14b16VPjr5Ra/Z69XTXQLu/nxVVZbiTSCsZ7tFE+WeVl22sL0oSRMUYpV8eMC7p3PFzzJQqsdTBJ944Ja0s6PFBCmumCiTwVppkBKsTdmmOktecGVmCUzYUSuZZRg3aJnITbmQgF/DlrTvhsYuagd52AqoLk5u5UBtGObqxIGHUhE/QmvbHfADcQvclu7jWzHHqwGYIR7/MtFksAImrLtbgNdZasfAP06bq7SvUtnKTW+fvAYtrSyEDTHvBkUWS+zwcpBDvL7ozlnRQvgxCYY7YSKZeDb5glAilNb1KUOfZccwqD56shmA77oopozVeIVhV3VKxpdJhwY98ApHiSBhXBGf5gblO1R4IPT+6B6fxXl3v5T58YtAoWRe9H8kOrP2Tvt/O+xr1iO7L0Ub6U9Q5ukyBImJskVVa2sbt3QO+dX7c4Eppxils8W//q4cGLRWctkf562E0HOnZBmnq+Czz1pTJMMLtfuOEAE5s9sSKoXLHHqJZ/ManHF5VwMHt1IA2smuRBQD4qyq+X8lPrG4/Ao6vMfwRouvi3hH0/4dYDc=
  file_glob: true
  file: build/FakerDynamicValue-*.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: REBELinBLUE/Paw-FakerDynamicValue
