os: linux
dist: xenial

language: node_js

script:
  - NODE_ENV=production make build
  - make lint
  - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make archive

deploy:
  provider: releases
  api_key:
    secure: bxp1e+q8HTD04T74tU6K7yfZu00wBhA2aNKvy4cLPOkQ7BQVxHLpjo9vTkL/Tom/PMAmPm5faN0YGfJc2bCUtd758aViobGJC3MPwjPKPs2dKXwjzJT9OQvSFIFzq/YbfoXy7wAS9+8wqRoPVKuwmibVeYd3Pk2A/+NYZnaBtLwbX5sddK1X2l1gee/PAtFFDPjUsbxC+f/AuNNpsSVeZKqEaCq/eCOd09/AqG49afN2f+mZARElY87u333kVLECXPyT0U8TWhDvrb8DqjehBdDaUA/3KdFlYoX8JNebZmr2RPJRso+QuAYkQFwxkNLNZHBIzi2HlCsGvmD5AsX7nnUkEnh2B8ygEXJz9I0jWhJl3uZ9DJmW84FlmVQCtRabhWAfa1+gM6u9BY1zKvnq56tXLwqbZnz87JTcbTPCyK9blqLDOf2/wM6nEomd1NLEp3o6aLKqWWi60Guw1BueWkBcaVjDX3KzQ1627Jp5/MbmvVm8PWgHh8TijodwTSWjTxDkqr2dicndvPWVpYGRu2ZDkg/W3ldwitB5b8QZKlGHKuhPyRORBZZDtRFrPEbCZXpzoMi8dpR8TXdGaJ7UTGA+LDTAGg3JpaZjZ8GYZDIWdsiNmPci4BFD2MpOtcZdcTIz/DdxTqleVlMRVdo9bhwuLNovCpIjO3GOM2EoylA=
  file_glob: true
  file: build/FakerDynamicValue-*.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: REBELinBLUE/Paw-FakerDynamicValue
